// Generated by gencpp from file camera_control_msgs/GrabImagesFeedback.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_GRABIMAGESFEEDBACK_H
#define CAMERA_CONTROL_MSGS_MESSAGE_GRABIMAGESFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_control_msgs
{
template <class ContainerAllocator>
struct GrabImagesFeedback_
{
  typedef GrabImagesFeedback_<ContainerAllocator> Type;

  GrabImagesFeedback_()
    : curr_nr_images_taken(0)  {
    }
  GrabImagesFeedback_(const ContainerAllocator& _alloc)
    : curr_nr_images_taken(0)  {
  (void)_alloc;
    }



   typedef int32_t _curr_nr_images_taken_type;
  _curr_nr_images_taken_type curr_nr_images_taken;





  typedef boost::shared_ptr< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GrabImagesFeedback_

typedef ::camera_control_msgs::GrabImagesFeedback_<std::allocator<void> > GrabImagesFeedback;

typedef boost::shared_ptr< ::camera_control_msgs::GrabImagesFeedback > GrabImagesFeedbackPtr;
typedef boost::shared_ptr< ::camera_control_msgs::GrabImagesFeedback const> GrabImagesFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'camera_control_msgs': ['/home/casch/ws_moveit/devel/share/camera_control_msgs/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "416670c64a4018bd170bd09a7dd5f0c4";
  }

  static const char* value(const ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x416670c64a4018bdULL;
  static const uint64_t static_value2 = 0x170bd09a7dd5f0c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_control_msgs/GrabImagesFeedback";
  }

  static const char* value(const ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"##########################################\n"
"################ FEEDBACK ################\n"
"##########################################\n"
"# The number of images already taken\n"
"int32 curr_nr_images_taken\n"
"\n"
;
  }

  static const char* value(const ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.curr_nr_images_taken);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrabImagesFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_control_msgs::GrabImagesFeedback_<ContainerAllocator>& v)
  {
    s << indent << "curr_nr_images_taken: ";
    Printer<int32_t>::stream(s, indent + "  ", v.curr_nr_images_taken);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_GRABIMAGESFEEDBACK_H
