// Generated by gencpp from file camera_control_msgs/SetGamma.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_SETGAMMA_H
#define CAMERA_CONTROL_MSGS_MESSAGE_SETGAMMA_H

#include <ros/service_traits.h>


#include <camera_control_msgs/SetGammaRequest.h>
#include <camera_control_msgs/SetGammaResponse.h>


namespace camera_control_msgs
{

struct SetGamma
{

typedef SetGammaRequest Request;
typedef SetGammaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGamma
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::SetGamma > {
  static const char* value()
  {
    return "d071cb93e1f4c5737ce40debcd7942a5";
  }

  static const char* value(const ::camera_control_msgs::SetGamma&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::SetGamma > {
  static const char* value()
  {
    return "camera_control_msgs/SetGamma";
  }

  static const char* value(const ::camera_control_msgs::SetGamma&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::SetGammaRequest> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetGamma > 
template<>
struct MD5Sum< ::camera_control_msgs::SetGammaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetGamma >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGammaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetGammaRequest> should match 
// service_traits::DataType< ::camera_control_msgs::SetGamma > 
template<>
struct DataType< ::camera_control_msgs::SetGammaRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetGamma >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGammaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::SetGammaResponse> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetGamma > 
template<>
struct MD5Sum< ::camera_control_msgs::SetGammaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetGamma >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGammaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetGammaResponse> should match 
// service_traits::DataType< ::camera_control_msgs::SetGamma > 
template<>
struct DataType< ::camera_control_msgs::SetGammaResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetGamma >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGammaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_SETGAMMA_H
