// Generated by gencpp from file camera_control_msgs/SetGain.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_SETGAIN_H
#define CAMERA_CONTROL_MSGS_MESSAGE_SETGAIN_H

#include <ros/service_traits.h>


#include <camera_control_msgs/SetGainRequest.h>
#include <camera_control_msgs/SetGainResponse.h>


namespace camera_control_msgs
{

struct SetGain
{

typedef SetGainRequest Request;
typedef SetGainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGain
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::SetGain > {
  static const char* value()
  {
    return "20482afb1d808bae25db22114b0a747f";
  }

  static const char* value(const ::camera_control_msgs::SetGain&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::SetGain > {
  static const char* value()
  {
    return "camera_control_msgs/SetGain";
  }

  static const char* value(const ::camera_control_msgs::SetGain&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::SetGainRequest> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetGain > 
template<>
struct MD5Sum< ::camera_control_msgs::SetGainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetGain >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetGainRequest> should match 
// service_traits::DataType< ::camera_control_msgs::SetGain > 
template<>
struct DataType< ::camera_control_msgs::SetGainRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetGain >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::SetGainResponse> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetGain > 
template<>
struct MD5Sum< ::camera_control_msgs::SetGainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetGain >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetGainResponse> should match 
// service_traits::DataType< ::camera_control_msgs::SetGain > 
template<>
struct DataType< ::camera_control_msgs::SetGainResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetGain >::value();
  }
  static const char* value(const ::camera_control_msgs::SetGainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_SETGAIN_H
