(cl:in-package camera_control_msgs-srv)
(cl:export '(SUCCESS-VAL
          SUCCESS
          IS_SLEEPING-VAL
          IS_SLEEPING
          DEVICE_USER_ID-VAL
          DEVICE_USER_ID
          MIN_BINNING_X-VAL
          MIN_BINNING_X
          MAX_BINNING_X-VAL
          MAX_BINNING_X
          CURRENT_BINNING_X-VAL
          CURRENT_BINNING_X
          MIN_BINNING_Y-VAL
          MIN_BINNING_Y
          MAX_BINNING_Y-VAL
          MAX_BINNING_Y
          CURRENT_BINNING_Y-VAL
          CURRENT_BINNING_Y
          MAX_FRAMERATE-VAL
          MAX_FRAMERATE
          CURRENT_FRAMERATE-VAL
          CURRENT_FRAMERATE
          MIN_EXPOSURE-VAL
          MIN_EXPOSURE
          MAX_EXPOSURE-VAL
          MAX_EXPOSURE
          CURRENT_EXPOSURE-VAL
          CURRENT_EXPOSURE
          MIN_GAIN_IN_CAM_UNITS-VAL
          MIN_GAIN_IN_CAM_UNITS
          MAX_GAIN_IN_CAM_UNITS-VAL
          MAX_GAIN_IN_CAM_UNITS
          CURRENT_GAIN_IN_CAM_UNITS-VAL
          CURRENT_GAIN_IN_CAM_UNITS
          MIN_GAIN-VAL
          MIN_GAIN
          MAX_GAIN-VAL
          MAX_GAIN
          CURRENT_GAIN-VAL
          CURRENT_GAIN
          MIN_GAMMA-VAL
          MIN_GAMMA
          MAX_GAMMA-VAL
          MAX_GAMMA
          CURRENT_GAMMA-VAL
          CURRENT_GAMMA
          BRIGHTNESS_CONTINUOUS-VAL
          BRIGHTNESS_CONTINUOUS
          GAIN_AUTO-VAL
          GAIN_AUTO
          EXPOSURE_AUTO-VAL
          EXPOSURE_AUTO
))