// Auto-generated. Do not edit!

// (in-package camera_control_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GrabHDRImageFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.curr_nr_images_taken = null;
    }
    else {
      if (initObj.hasOwnProperty('curr_nr_images_taken')) {
        this.curr_nr_images_taken = initObj.curr_nr_images_taken
      }
      else {
        this.curr_nr_images_taken = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GrabHDRImageFeedback
    // Serialize message field [curr_nr_images_taken]
    bufferOffset = _serializer.int32(obj.curr_nr_images_taken, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GrabHDRImageFeedback
    let len;
    let data = new GrabHDRImageFeedback(null);
    // Deserialize message field [curr_nr_images_taken]
    data.curr_nr_images_taken = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'camera_control_msgs/GrabHDRImageFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '416670c64a4018bd170bd09a7dd5f0c4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    ##########################################
    ################ FEEDBACK ################
    ##########################################
    int32 curr_nr_images_taken
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GrabHDRImageFeedback(null);
    if (msg.curr_nr_images_taken !== undefined) {
      resolved.curr_nr_images_taken = msg.curr_nr_images_taken;
    }
    else {
      resolved.curr_nr_images_taken = 0
    }

    return resolved;
    }
};

module.exports = GrabHDRImageFeedback;
