// Generated by gencpp from file camera_control_msgs/SetBool.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_SETBOOL_H
#define CAMERA_CONTROL_MSGS_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <camera_control_msgs/SetBoolRequest.h>
#include <camera_control_msgs/SetBoolResponse.h>


namespace camera_control_msgs
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::SetBool > {
  static const char* value()
  {
    return "09fb03525b03e7ea1fd3992bafd87e16";
  }

  static const char* value(const ::camera_control_msgs::SetBool&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::SetBool > {
  static const char* value()
  {
    return "camera_control_msgs/SetBool";
  }

  static const char* value(const ::camera_control_msgs::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::SetBoolRequest> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetBool > 
template<>
struct MD5Sum< ::camera_control_msgs::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetBool >::value();
  }
  static const char* value(const ::camera_control_msgs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetBoolRequest> should match 
// service_traits::DataType< ::camera_control_msgs::SetBool > 
template<>
struct DataType< ::camera_control_msgs::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetBool >::value();
  }
  static const char* value(const ::camera_control_msgs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::SetBoolResponse> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetBool > 
template<>
struct MD5Sum< ::camera_control_msgs::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetBool >::value();
  }
  static const char* value(const ::camera_control_msgs::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetBoolResponse> should match 
// service_traits::DataType< ::camera_control_msgs::SetBool > 
template<>
struct DataType< ::camera_control_msgs::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetBool >::value();
  }
  static const char* value(const ::camera_control_msgs::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_SETBOOL_H
