// Generated by gencpp from file camera_control_msgs/SetSleeping.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_SETSLEEPING_H
#define CAMERA_CONTROL_MSGS_MESSAGE_SETSLEEPING_H

#include <ros/service_traits.h>


#include <camera_control_msgs/SetSleepingRequest.h>
#include <camera_control_msgs/SetSleepingResponse.h>


namespace camera_control_msgs
{

struct SetSleeping
{

typedef SetSleepingRequest Request;
typedef SetSleepingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSleeping
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::SetSleeping > {
  static const char* value()
  {
    return "f51754709312645db79ada18bc0254a3";
  }

  static const char* value(const ::camera_control_msgs::SetSleeping&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::SetSleeping > {
  static const char* value()
  {
    return "camera_control_msgs/SetSleeping";
  }

  static const char* value(const ::camera_control_msgs::SetSleeping&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::SetSleepingRequest> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetSleeping > 
template<>
struct MD5Sum< ::camera_control_msgs::SetSleepingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetSleeping >::value();
  }
  static const char* value(const ::camera_control_msgs::SetSleepingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetSleepingRequest> should match 
// service_traits::DataType< ::camera_control_msgs::SetSleeping > 
template<>
struct DataType< ::camera_control_msgs::SetSleepingRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetSleeping >::value();
  }
  static const char* value(const ::camera_control_msgs::SetSleepingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::SetSleepingResponse> should match 
// service_traits::MD5Sum< ::camera_control_msgs::SetSleeping > 
template<>
struct MD5Sum< ::camera_control_msgs::SetSleepingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetSleeping >::value();
  }
  static const char* value(const ::camera_control_msgs::SetSleepingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetSleepingResponse> should match 
// service_traits::DataType< ::camera_control_msgs::SetSleeping > 
template<>
struct DataType< ::camera_control_msgs::SetSleepingResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetSleeping >::value();
  }
  static const char* value(const ::camera_control_msgs::SetSleepingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_SETSLEEPING_H
